### PR TITLE
Update CBLEncoder to Open

### PR DESCRIPTION
**Pull request by danieltarazona**
Update CBLEncoder to Open Protection Level.
https://cocoacasts.com/what-is-the-difference-between-public-and-open-in-swift-3/

### CODE REVIEW

**Comment by marcblanchet** [comment]
this patch is necessary for this package to be useful. please merge.

**Comment by danieltarazona** [comment]
@marcblanchet I don't have write access to this repo.

**Comment by danieltarazona** [comment]
@pasin Could you help me here?

**Review by pasin — APPROVED** [review]

**Comment by pasin** [comment]
Done.

**Pull request merged**
